### ISSUE TITLE
"All arrays must be of same length"

### ISSUE THREAD

**Issue by chrisroederucdenver** [chrisroederucdenver/CCDA_OMOP_by_Python#31]
layer_datasets.py crashes when run on ToC_CCDA_CCD_CompGuideSample_FullXML.xml'

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/roederc/work/git_clad_test/CCDA_OMOP_by_Python/prototype_2/layer_datasets.py", line 96, in <module>
    dataframe_dict = create_omop_domain_dataframes(omop_data, filepath)
  File "/Users/roederc/work/git_clad_test/CCDA_OMOP_by_Python/prototype_2/layer_datasets.py", line 39, in create_omop_domain_dataframes
    domain_df = PD.DataFrame(column_dict)
  File "/Users/roederc/Library/Python/3.9/lib/python/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/Users/roederc/Library/Python/3.9/lib/python/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/Users/roederc/Library/Python/3.9/lib/python/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/Users/roederc/Library/Python/3.9/lib/python/site-packages/pandas/core/internals/construction.py", line 677, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length

**Comment by croeder** [comment]
the ToC file doesn't always create a value for each of value_as_number, value_as_string, value_as_concept_id, even if None.
We need these so the dataframe of columns and rows for a particular table is square and each row has a colum for each row.

**Comment by croeder** [comment]
layer_datasets was creating a pandas dataframe from multiple rows for measurement, and one of them had one less column. the reason had to do with a derived field being created from a null value. The code didn't put the null/None into the return struct.
